[[redirects]]
  from = "/lessons"
  to = "/"
  status = 401
  force = true
  conditions = {Role = []}

  from = "/class-admin"
  to = "/"
  status = 401
  force = true
  conditions = {Role = ["","student"]}