[[redirects]]
  from = "/lessons/*"
  to = "/lessons/:splat"
  status = 200
  force = true
  conditions = {Roles = ["student","instructor"]}

[[redirects]]
  from = "/lessons/*"
  to = "/lessons"
  status = 302
  force = true
